version: '3'

services:
  selenium-hub:
    image: selenium/hub
    ports:
      - "4442-4444:4442-4444"
    networks:
      - grid
			
 node-chrome: #similarly we can add n number of nodes based on requirment only node image name will be diff like node-edge
   image: selenium/node-chrome
   environment:
     - SE_EVENT_BUS_HOST=selenium-hub
     - SE_EVENT_BUS_PUBLISH_PORT=4442
     - SE_EVENT_BUS_SUBCRIBE_PORT=4443
   networks:
     - grid
		
 node-firefox:
   image: selenium/node-firefox
   environment:
     - SE_EVENT_BUS_HOST=selenium-hub
     - SE_EVENT_BUS_PUBLISH_PORT=4442
     - SE_EVENT_BUS_SUBCRIBE_PORT=4443
   networks:
     - grid

	 
networks:
  grid:
    driver: bridge
					
  
  

